### ISSUE TITLE
Toodledoodledoo naming convention lost 

### ISSUE THREAD

**Issue by balbyu** [ojjo-sh/toodledoodledoo#13]
Although it's a little more work, we should use the words `todoodle` & `toodledoodledo` in place of `todo / todos`. 

The whole point of naming this project **toodledoodledo** was to make the developing a todo application that wasn't in the doldrums...

**Comment by ttylta** [comment]
I'm open to having a discussion about this. I personally think Toodledoodledoo is better suited as a name for the application, rather than a name for its entities.

**Comment by opmorgan** [comment]
I think we should consider toodledoodledoodledoo.

**Comment by balbyu** [comment]
Closed due to inactivity.
