### ISSUE TITLE
Use async/await for processing requests

### ISSUE THREAD

**Issue by ttylta** [ojjo-sh/toodledoodledoo#3]
Right now we're using promises and/or callbacks. Read this: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

An example:
```Javascript
app.get(`/${apiPrefix}/todos`, async (req, res) => {
  const q = 'SELECT * FROM todos';

  try {
    const result = await pool.query(q);
    res.status(200).json(result.rows);
  } catch (err) {
    throw err;
  }
});
```

**Comment by balbyu** [comment]
Finished developing today, but couldn't test :(((((((

**Comment by balbyu** [comment]
does.... does this mean I'm not a professional developer????
